### ISSUE TITLE
`Hello World` example

### ISSUE THREAD

**Issue by EZoni** [AMReX-Codes/pyamrex#143]
Discussed with @kngott, right now we have no `amrex::Print` wrapper that makes a good "Hello World!" example. What do we want to do for a "Hello World!" example?

**Comment by ax3l** [comment]
Thanks @EZoni.

This can probably be closed now.

We implemented `amrex::Print` in #174 and have the examples now documented / listed in https://pyamrex.readthedocs.io/en/latest/usage/how_to_run.html
