### ISSUE TITLE
bindings for PlotFileData

### ISSUE THREAD

**Issue by BenWibking** [AMReX-Codes/pyamrex#317]
Are there any plans to add bindings for `amrex::AmrData` (https://github.com/AMReX-Codes/amrex/blob/af6e77226cdb1668a8936ee3b35cf0d441409869/Src/Extern/amrdata/AMReX_AmrData.H) in order to read plotfiles via Python?

Ideally, I'd like to be able to write an equivalent of https://github.com/openPMD/openPMD-viewer for AMReX plotfiles.

Or, is there any other API to read plotfiles that would be faster to get started with?

**Comment by WeiqunZhang** [comment]
Maybe you can try to port PlotFileData to pyamrex.

**Comment by BenWibking** [comment]
@WeiqunZhang @ax3l Is there any way to lazily load individual FABs?

It looks like PlotFileUtil loads the entire MultiFab into memory at once. This is fine for 2D plotfiles, but won't work for 3D plotfiles when used with https://github.com/BenWibking/plotfile-viewer.
