### ISSUE TITLE
bindings for reading particle data

### ISSUE THREAD

**Issue by BenWibking** [AMReX-Codes/pyamrex#328]
Is there an appropriate C++ API that can be used to read particle data, similar to https://github.com/AMReX-Codes/pyamrex/pull/320?

The use case is to visualize particles with plotfile-viewer: https://github.com/BenWibking/plotfile-viewer.

**Comment by BenWibking** [comment]
cc @ax3l

**Comment by ax3l** [comment]
cc @atmyers 😁

**Comment by atmyers** [comment]
Hi @BenWibking,

The code for reading particles is the `Restart` method of `ParticleContainer`, implemented [here](https://github.com/AMReX-Codes/amrex/blob/development/Src/Particle/AMReX_ParticleIO.H#L644). There's also a test that shows how to use it [here](https://github.com/AMReX-Codes/amrex/blob/development/Tests/HDF5Benchmark/main.cpp).

**Comment by BenWibking** [comment]
@atmyers thanks!

**Comment by JBlaschke** [comment]
@ax3l @BenWibking is there any progress on this? If not, what can we contribute to speed things up?

also tagging @ajnonaka, @drladiges @quintonfis @laurensowards

**Comment by ax3l** [comment]
Status is as follows: #320 merged two days ago and in 24.07 release.

The linked methods from Andrew's post are very easy to add. Please go ahead and post a PR - contributions are super welcome 💖. I am on PTO and back on July 15th, so this can totally land in 24.08 if someone takes the lead to add a few more .def method bindings and a good test 🙏

**Comment by BenWibking** [comment]
Should be closed by https://github.com/AMReX-Codes/pyamrex/pull/342 (except for any app-specific template instantiations).
